// src/app/lab/drafts/page.tsx
import { CockpitShell } from "@/components/cockpit/cockpit-shell";
import { getServiceClient } from "@/lib/supabase/server";
import { listVideosByStatus } from "@/lib/supabase/repositories/your-videos";
import type { VideoStatus } from "@/lib/supabase/repositories/your-videos";
import { DraftsTabs, type DraftsTab } from "@/components/lab/drafts-tabs";
import { DraftRow } from "@/components/lab/draft-row";
import { RenderedRow } from "@/components/lab/rendered-row";
import { ScheduledRow } from "@/components/lab/scheduled-row";
import { PostedRow } from "@/components/lab/posted-row";

export const dynamic = "force-dynamic";

export default async function LabDraftsPage({
  searchParams,
}: {
  searchParams: Promise<{ tab?: string }>;
}) {
  const { tab } = await searchParams;
  const active: DraftsTab =
    tab === "rendered" || tab === "posted" || tab === "scheduled" ? tab : "draft";

  const supabase = getServiceClient();
  const statusFor: Record<DraftsTab, VideoStatus | VideoStatus[]> = {
    draft: ["draft", "rendering"],
    rendered: "rendered",
    scheduled: ["scheduled", "uploading"],
    posted: "posted",
  };
  const videos = await listVideosByStatus(supabase, statusFor[active], 20);

  return (
    <CockpitShell>
      <div className="p-6 space-y-6 max-w-5xl mx-auto">
        <header>
          <h1 className="text-2xl font-semibold text-text-primary">Drafts</h1>
          <p className="text-text-secondary text-sm mt-1">
            Render, review, and approve videos generated by The Lab pipeline.
          </p>
        </header>

        <DraftsTabs active={active} />

        <section className="rounded-lg border border-subtle bg-surface">
          {videos.length === 0 ? (
            <p className="px-4 py-6 text-sm text-text-muted">
              {active === "draft" && "No drafts. Dispatch a topic from /lab to make one."}
              {active === "rendered" && "No rendered videos yet. Render a draft to see it here."}
              {active === "scheduled" && "No scheduled videos yet. Approve a rendered video to schedule it."}
              {active === "posted" && "No posted videos yet."}
            </p>
          ) : (
            <ul className="divide-y divide-subtle">
              {videos.map((v) => {
                if (active === "draft") return <DraftRow key={v.id} draft={v} />;
                if (active === "rendered") return <RenderedRow key={v.id} video={v} />;
                if (active === "scheduled") return <ScheduledRow key={v.id} video={v} />;
                return <PostedRow key={v.id} video={v} />;
              })}
            </ul>
          )}
        </section>
      </div>
    </CockpitShell>
  );
}
