// src/app/lab/drafts/page.tsx
//
// Draft pipeline review. Tabs (Draft / Rendered / Scheduled / Posted) are
// driven by ?tab=<key>. All tabs render through the premium DraftRow component
// for consistent verdict badges, status pills, and status-appropriate actions.

import { FileText, Film, CalendarClock, Send } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { PageHeader } from "@/components/layout/page-header";
import { getServiceClient } from "@/lib/supabase/server";
import {
  listVideosByStatusWithVerdict,
} from "@/lib/supabase/repositories/your-videos";
import type { VideoStatus } from "@/lib/supabase/repositories/your-videos";
import { DraftsTabs, type DraftsTab } from "@/components/lab/drafts-tabs";
import { DraftsList } from "@/components/lab/drafts-list";
import { DraftRow } from "@/components/lab/draft-row";
import { toDraftRow } from "@/lib/lab/drafts-view";

export const dynamic = "force-dynamic";

const EMPTY: Record<DraftsTab, { icon: LucideIcon; title: string; body: string }> = {
  draft: {
    icon: FileText,
    title: "No drafts yet",
    body: "Dispatch a reviewed topic from The Lab and the finished draft will land here, ready to render.",
  },
  rendered: {
    icon: Film,
    title: "No rendered videos yet",
    body: "Render a draft and it shows up here for review — approve to schedule, or post it now.",
  },
  scheduled: {
    icon: CalendarClock,
    title: "No scheduled videos yet",
    body: "Approve a rendered video to queue it. Scheduled posts and their countdowns appear here.",
  },
  posted: {
    icon: Send,
    title: "No posted videos yet",
    body: "Once a video goes live, it lands here with its analytics — views, watch time, and CTR.",
  },
};

export default async function LabDraftsPage({
  searchParams,
}: {
  searchParams: Promise<{ tab?: string }>;
}) {
  const { tab } = await searchParams;
  const active: DraftsTab =
    tab === "rendered" || tab === "posted" || tab === "scheduled" ? tab : "draft";

  const supabase = getServiceClient();
  const statusFor: Record<DraftsTab, VideoStatus | VideoStatus[]> = {
    draft: ["draft", "rendering"],
    rendered: "rendered",
    scheduled: ["scheduled", "uploading"],
    posted: "posted",
  };
  const videos = await listVideosByStatusWithVerdict(supabase, statusFor[active], 20);

  const rows = videos.map((v) =>
    toDraftRow({
      id: v.id,
      title: v.title,
      status: v.status,
      review_verdict: v.overall_verdict,
      thumbnail_url: v.render_artifact_url,
      scheduled_for: v.scheduled_for,
    }),
  );

  const empty = EMPTY[active];

  return (
    <AppShell bare sidebar={<AppSidebar activeHref="/lab" />}>
      <div className="mx-auto max-w-[1080px] px-8 py-8">
        <PageHeader
          title="Drafts"
          description="Render, review, and approve videos generated by The Lab pipeline."
        />

        <div className="mb-6">
          <DraftsTabs active={active} />
        </div>

        {rows.length === 0 ? (
          <EmptyState
            icon={empty.icon}
            title={empty.title}
            body={empty.body}
          />
        ) : (
          <DraftsList>
            {rows.map((row, i) => (
              <DraftRow
                key={row.id}
                row={row}
                index={i}
                orchestrated
              />
            ))}
          </DraftsList>
        )}
      </div>
    </AppShell>
  );
}

function EmptyState({
  icon: Icon,
  title,
  body,
}: {
  icon: LucideIcon;
  title: string;
  body: string;
}) {
  return (
    <div className="flex flex-col items-center justify-center gap-4 rounded-xl border border-dashed border-[var(--border-subtle)] bg-[var(--surface-1)]/40 px-8 py-16 text-center">
      <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-1)]">
        <Icon className="h-5 w-5 text-[var(--text-tertiary)]" aria-hidden />
      </div>
      <div>
        <p className="text-sm font-medium text-[var(--text-primary)]">{title}</p>
        <p className="mx-auto mt-1 max-w-sm text-sm text-[var(--text-secondary)]">{body}</p>
      </div>
    </div>
  );
}
