// src/app/lab/drafts/page.tsx
//
// Draft pipeline review. Tabs (Draft / Rendered / Scheduled / Posted) are
// driven by ?tab=<key>. Data fetching (listVideosByStatus) and the server/
// client boundary are preserved exactly — presentation only is rebuilt.

import { FileText, Film, CalendarClock, Send } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { PageHeader } from "@/components/layout/page-header";
import { getServiceClient } from "@/lib/supabase/server";
import { listVideosByStatus } from "@/lib/supabase/repositories/your-videos";
import type { VideoStatus } from "@/lib/supabase/repositories/your-videos";
import { DraftsTabs, type DraftsTab } from "@/components/lab/drafts-tabs";
import { DraftsList } from "@/components/lab/drafts-list";
import { DraftRow } from "@/components/lab/draft-row";
import { toDraftRow } from "@/lib/lab/drafts-view";
import { RenderedRow } from "@/components/lab/rendered-row";
import { ScheduledRow } from "@/components/lab/scheduled-row";
import { PostedRow } from "@/components/lab/posted-row";

export const dynamic = "force-dynamic";

const EMPTY: Record<DraftsTab, { icon: LucideIcon; title: string; body: string }> = {
  draft: {
    icon: FileText,
    title: "No drafts yet",
    body: "Dispatch a reviewed topic from The Lab and the finished draft will land here, ready to render.",
  },
  rendered: {
    icon: Film,
    title: "No rendered videos yet",
    body: "Render a draft and it shows up here for review — approve to schedule, or post it now.",
  },
  scheduled: {
    icon: CalendarClock,
    title: "No scheduled videos yet",
    body: "Approve a rendered video to queue it. Scheduled posts and their countdowns appear here.",
  },
  posted: {
    icon: Send,
    title: "No posted videos yet",
    body: "Once a video goes live, it lands here with its analytics — views, watch time, and CTR.",
  },
};

export default async function LabDraftsPage({
  searchParams,
}: {
  searchParams: Promise<{ tab?: string }>;
}) {
  const { tab } = await searchParams;
  const active: DraftsTab =
    tab === "rendered" || tab === "posted" || tab === "scheduled" ? tab : "draft";

  const supabase = getServiceClient();
  const statusFor: Record<DraftsTab, VideoStatus | VideoStatus[]> = {
    draft: ["draft", "rendering"],
    rendered: "rendered",
    scheduled: ["scheduled", "uploading"],
    posted: "posted",
  };
  const videos = await listVideosByStatus(supabase, statusFor[active], 20);

  const empty = EMPTY[active];

  return (
    <AppShell bare sidebar={<AppSidebar activeHref="/lab" />}>
      <div className="mx-auto max-w-[1080px] px-8 py-8">
        <PageHeader
          title="Drafts"
          description="Render, review, and approve videos generated by The Lab pipeline."
        />

        <div className="mb-6">
          <DraftsTabs active={active} />
        </div>

        {videos.length === 0 ? (
          <EmptyState
            icon={empty.icon}
            title={empty.title}
            body={empty.body}
          />
        ) : active === "posted" ? (
          // Posted rows are server components — render in a static styled list.
          <ul className="overflow-hidden rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-1)] shadow-[var(--elev-1)]">
            {videos.map((v) => (
              <PostedRow key={v.id} video={v} />
            ))}
          </ul>
        ) : (
          <DraftsList>
            {videos.map((v, i) => {
              if (active === "draft")
                return (
                  <DraftRow
                    key={v.id}
                    row={toDraftRow({
                      id: v.id,
                      title: v.title,
                      status: v.status,
                      review_verdict: null,
                      thumbnail_url: v.render_artifact_url,
                    })}
                    index={i}
                  />
                );
              if (active === "rendered") return <RenderedRow key={v.id} video={v} />;
              return <ScheduledRow key={v.id} video={v} />;
            })}
          </DraftsList>
        )}
      </div>
    </AppShell>
  );
}

function EmptyState({
  icon: Icon,
  title,
  body,
}: {
  icon: LucideIcon;
  title: string;
  body: string;
}) {
  return (
    <div className="flex flex-col items-center justify-center gap-4 rounded-xl border border-dashed border-[var(--border-subtle)] bg-[var(--surface-1)]/40 px-8 py-16 text-center">
      <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-1)]">
        <Icon className="h-5 w-5 text-[var(--text-tertiary)]" aria-hidden />
      </div>
      <div>
        <p className="text-sm font-medium text-[var(--text-primary)]">{title}</p>
        <p className="mx-auto mt-1 max-w-sm text-sm text-[var(--text-secondary)]">{body}</p>
      </div>
    </div>
  );
}
